import win32com.client
import os
import datetime as dt



def open_excel_file(file_name):
    """Function to create/instantiate excel file in background"""

    xl = win32com.client.DispatchEx("Excel.Application")
    xl.Visible = 0
    xl.DisplayAlerts = False
    wb = xl.Workbooks.Open(file_name)
    xl.ActiveWindow.DisplayGridlines = False

    """Write into excel HEADER"""
    sheet = wb.Worksheets.Add()
    wb.Worksheets(1).Name = 'Cover'

    return xl, wb, sheet

def paste_plot(xl,wb):

    sheet = wb.Sheets('Commentary')
    wb.Worksheets('Commentary').Activate()
    top = sheet.Cells(1, 9).Top;
    left = sheet.Cells(1, 9).Left  # To get the Top & Left coordinates

    xl.ActiveSheet.Shapes.AddPicture(f'{os.environ["USERPROFILE"]}\\plot.png', False, True, left,
                                     top,
                                     -1, -1)

    sheet.Cells(1, 1).Select()
    wb.ActiveSheet.Rows(1).Insert()
    wb.ActiveSheet.Rows(1).Insert()
    wb.ActiveSheet.Rows(1).Insert()
    wb.ActiveSheet.Rows(1).Insert()
    wb.ActiveSheet.Rows(1).Insert()

    xl.ActiveWorkbook.ActiveSheet.Columns("A:I").AutoFit()

    sheet.Cells(2, 1).Value = "Threshold is 1M USD of monthly Fluctuation"
    sheet.Cells(3,
                1).Value = "This tab displays only required lines to comment."

    sheet.Cells(4,
                1).Value = "HAVE FUN !! :D "



    wb.Worksheets('Cover').Activate()

def init_structure(xl,wb,sheet,RU,year,period,currency):
    """ Function to build up the reconciliation sheet structure"""
    sheet.Select()
    sheet.Cells(2, 2).Value = "Forex Analysis Tool"
    sheet.Cells(3, 2).Value = "This working paper was generated by a tool, designed to assist in forex analysis"
    sheet.Cells(4, 2).Value = f"Created by : {os.environ['USERNAME'].upper()} at : {dt.datetime.today()}"

    sheet.Cells(6, 2).Value = "Parameters used in this tool:"
    sheet.Cells(7, 2).Value = f"RU : {RU}  Year : {year}  Period: {period}"

    sheet.Cells(8, 2).Value = f"Scale parameter is $ 1,000,000 (M) USD : $1 USD"

    if currency != 'USD':
        paste_plot(xl,wb)

def format_cells(xl,wb):
    c = win32com.client.constants

    sheet = wb.Sheets('Commentary')
    sheet.Select()
    sheet.Columns("D:G").NumberFormat = "#,##0.0"
    xl.ActiveWindow.DisplayGridlines = False

    sheet = wb.Sheets('Totals')
    sheet.Select()
    xl.ActiveWindow.DisplayGridlines = False
    sheet.Columns("B:D").NumberFormat = "#,##0.0"
    xl.ActiveWorkbook.ActiveSheet.Columns("A:I").AutoFit()

    sheet = wb.Sheets('Realized Forex')
    sheet.Select()
    xl.ActiveWindow.DisplayGridlines = False
    sheet.Columns("D:F").NumberFormat = "#,##0.0"
    xl.ActiveWorkbook.ActiveSheet.Columns("A:I").AutoFit()

    sheet = wb.Sheets('Unrealized Forex')
    sheet.Select()
    xl.ActiveWindow.DisplayGridlines = False
    sheet.Columns("D:F").NumberFormat = "#,##0.0"
    xl.ActiveWorkbook.ActiveSheet.Columns("A:I").AutoFit()

    sheet = wb.Sheets('Quotes')
    sheet.Select()
    xl.ActiveWindow.DisplayGridlines = False
    sheet.Columns("C:F").NumberFormat = "#,##0.00"

    sheet = wb.Sheets('Cover')
    sheet.Select()
    xl.ActiveWindow.DisplayGridlines = False
    xl.ActiveWorkbook.ActiveSheet.Columns("A:I").AutoFit()
    cell = sheet.Cells(8, 2)
    font = cell.Font
    font.Color = -16776961
    font.TintAndShade = 0
    font.Size = 14
    font.Bold = True

    interior = cell.Interior
    #interior.Pattern = c.xlSolid
    #interior.PatternColorIndex = c.xlAutomatic
    interior.Color = 65535
    interior.TintAndShade = 0
    interior.PatternTintAndShade = 0